name:                cubix-sample-app
version:             0.1.0.0
github:              "cubix-framework/cubix-sample-app"
license:             BSD3
author:              "James Koppel"
maintainer:          "jkoppel@mit.edu"
copyright:           "2019 James Koppel"

extra-source-files:
- README.md

description:  A very simple example Cubix app

dependencies:
- base >= 4.7 && < 5

executables:
  cubix-sample-app:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cubix
    - cubix-compdata