name:                uses-cubix
version:             0.1.0.0
github:              "githubuser/uses-cubix"
license:             BSD3
author:              "James Koppel"
maintainer:          "jkoppel@mit.edu"
copyright:           "2019 James Koppel"

extra-source-files:
- README.md

description:  An example of how to configure a package to use Cubix as a dependency

dependencies:
- base >= 4.7 && < 5

executables:
  uses-cubix:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cubix
    - language-javascript