resolver: lts-6.12

packages:
- .

extra-deps: 
- language-lua-0.10.0
- language-javascript-0.6.0.9
- language-dot-0.1.0
- fgl-5.5.3.0
- git: git@github.com:jkoppel/language-c.git
  commit: e5bdaaa8cbf28d09962ccd64a50808d8e5032f85
- git: git@github.com:jkoppel/language-java.git
  commit: 68e71843294b233c36b3cbe52d9b1e35a5898997
- git: git@github.com:bjpop/language-python.git
  commit: 9269c77ca67c52280314a122cae1b3fa1a044168
- git: git@github.com:jkoppel/cubix.git
  commit: f477beeca65e6aea0729c14d620c8d312f940c4e
  subdirs:
  - .
  - compdata
  - compstrat
  - comptrans